ID: mnist
type: dl
container: dl
cleanup: false
job-config:
  serve: true
  model_name: mnist
  data:
    placeholder:
      input_type: file
      data_type: image
      image_size: 28
      output_type: onehot
      onehot_size: 10
      in: train-images-idx3-ubyte.gz
      out: train-labels-idx1-ubyte.gz
  model: cnn
  layer:
    - op_type: network
      op: [conv, pool, conv, pool, fc, fc]
#      op_id: convs
      active_function: [relu, None, relu, None, relu, softmax]
      op_size:
        - [5, 5, 1, 3]
        - 2
        - [5, 5, 3, 5]
        - 2
        - [245, 100]
        - [100, 10]
  rate: 0.0001
  epoch: 1000
  display_step: 100
  optimizer: adam
  batch_size: 64